"""changed username to user_id

Revision ID: 5a1cfaaa062f
Revises: 93d30a0bf251
Create Date: 2022-08-18 12:17:15.764159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1cfaaa062f'
down_revision = '93d30a0bf251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
