"""Create all tables

Revision ID: 6394f3ae6fc0
Revises: 5a1cfaaa062f
Create Date: 2022-08-18 12:19:16.947799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6394f3ae6fc0'
down_revision = '5a1cfaaa062f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
