"""Create all

Revision ID: f4270ace5818
Revises: 26cafbf621f4
Create Date: 2022-08-18 12:46:43.680108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4270ace5818'
down_revision = '26cafbf621f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
