"""Create all tables

Revision ID: f88c9929d93d
Revises: 5a1cfaaa062f
Create Date: 2022-08-18 12:36:40.247573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88c9929d93d'
down_revision = '5a1cfaaa062f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
